# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"replace": "00_core.ipynb",
         "get_top_hundred": "00_core.ipynb",
         "pip_top_hundred": "00_core.ipynb",
         "val": "00_core.ipynb",
         "extr": "00_core.ipynb",
         "recclass": "00_core.ipynb",
         "fullname": "00_core.ipynb",
         "is_parent": "00_core.ipynb",
         "is_base": "00_core.ipynb",
         "cut_names": "00_core.ipynb",
         "cut": "00_core.ipynb",
         "create_df": "00_core.ipynb",
         "extract": "00_core.ipynb",
         "extract_one": "00_core.ipynb",
         "index_data": "00_search.ipynb",
         "index_batch": "00_search.ipynb",
         "embed_text": "00_search.ipynb",
         "query": "00_search.ipynb"}

modules = ["core.py",
           "search.py"]

doc_url = "https://omemaxim.github.io/doc_collection/"

git_url = "https://github.com/omemaxim/doc_collection/tree/master/"

def custom_doc_links(name): return None
