# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_top_hundred": "00_core.ipynb",
         "pip_top_hundred": "00_core.ipynb",
         "extract": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://omemaxim.github.io/doc_collection/"

git_url = "https://github.com/omemaxim/doc_collection/tree/master/"

def custom_doc_links(name): return None
